// Standard Starlight docs collection. The content under src/content/docs/ is
// GENERATED by scripts/sync-content.ts from packages/harness/docs and
// packages/commerce/docs — edit those sources, never the synced copies.

import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
